### ISSUE TITLE
Statistik Sida

### ISSUE THREAD

**Issue by Braggedtooth** [chas-academy/u02-redesign-acrobatic-cow#8]
innehåll.  Design . Mobilanpassa

**Comment by HenrikFrohm** [comment]
Har fixat mobilanpassning och design håller jag på att jobba på just nu. 
Vad tänkte du med innehåll?

**Comment by Braggedtooth** [comment]
Sidans innehåll bara inget särskilt

**Comment by HenrikFrohm** [comment]
Alright. Hur går det för dig?
